version = 1

[[analyzers]]
name = "java"
enabled = true

[analyzers.meta]
# Set your Java runtime version
runtime_version = "17"

# Enable test coverage metrics (optional)
# 👉 For Maven projects
[[test_reports]]
path = "target/site/jacoco/jacoco.xml"
format = "jacoco"


